/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package favorite_list_place.app

import favorite_list_place.utilities.StringUtils

import org.apache.commons.text.WordUtils

fun main() {
    val tokens = StringUtils.split(MessageUtils.getMessage())
    val result = StringUtils.join(tokens)
    println(WordUtils.capitalize(result))
}
